[package]
name = "ezsingbox"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
rand = "0.9"
rustls-acme = "0.14.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = "3"
uuid = { version = "1.19.0", features = ["v4"] }
x25519-dalek = "2.0.1"
